### PR TITLE
Stop adding --platforms for packages

### LINKED ISSUE #5252: The "--platforms" argument is not supported in package template.
## Steps to Reproduce
Create a new package:

Képernyőfotó 2021-02-09 - 7 40 37
Képernyőfotó 2021-02-09 - 7 37 52

## Version info

[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-arm, locale hu-HU)
    • Flutter version 1.26.0-17.3.pre at /opt/flutter
    • Framework revision 4b50ca7f7f (4 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 2 categories.

### PR DESCRIPTION
**Pull request by stevemessick**
PlatformsForm.kt changed a lot less than it looks. The formatter changed a lot of indents. My change added a field `component` and an assignment to initialize it. That's so it can be disabled when `Package` type is selected.

Fixes #5252

### CODE REVIEW

File: src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java [hunk 1]
```diff
@@ -193,15 +194,23 @@ public FlutterCreateAdditionalSettings getAdditionalSettings() {
       .setOrg(!orgField.getText().trim().isEmpty() ? orgField.getText().trim() : null)
       .setSwift(iosLanguageRadios.isRadio2Selected() ? true : null)
       .setOffline(createParams.isOfflineSelected())
-      .setPlatformAndroid(platformsForm.shouldBeVisible() ? settings.getPlatformAndroid() : Boolean.TRUE)
-      .setPlatformIos(platformsForm.shouldBeVisible() ? settings.getPlatformIos() : Boolean.TRUE)
-      .setPlatformLinux(platformsForm.shouldBeVisible() ? settings.getPlatformLinux() : null)
-      .setPlatformMacos(platformsForm.shouldBeVisible() ? settings.getPlatformMacos() : null)
-      .setPlatformWeb(platformsForm.shouldBeVisible() ? settings.getPlatformWeb() : null)
-      .setPlatformWindows(platformsForm.shouldBeVisible() ? settings.getPlatformWindows() : null)
+      .setPlatformAndroid(shouldIncludPlatforms() ? settings.getPlatformAndroid() : Boolean.TRUE)
```
Comment (devoncarew) [inline src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java:197]: sp: `shouldIncludPlatforms `

**Review by devoncarew — APPROVED** [review]

File: src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java (hunk 1 above)
Comment (stevemessick) [reply src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java]: Thanks, fixed.
