### PR TITLE
Use --package-name in flutter create

### LINKED ISSUE #4352: [AndroidStudio wizard] Changing a "Package name" field works with bug
Editing the "Package name" field working with bug. Generated gradle file and xcode project contains applicationID/BundleId with original project name mixed with changed company domain. Next screenshots describing the way to represent error:

## Steps to Reproduce
Open wizard

Fill the fields -> Press Next

Here you see - Default values (ru.gs.flutter_app2)

Press Edit button, change Package name and press Done Button and then Finish button
[ru.gs.flutter_app2 changed to ru.gs2.app2]

Open xcode workspace and see the bug - BundleID not changed
[Let's be specific: the first part (company domain) is changed, the last is not]

Open app gradle file - ApplicationId not changed(same in manifest.xml)
[Let's be specific: the first part (company domain) is changed, the last is not]

## Version info

[✓] Flutter (Channel dev, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-RU)
    • Flutter version 1.14.6 at /Users/n/Tools/flutter
    • Framework revision fabeb2a16f (5 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/n/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

### PR DESCRIPTION
**Pull request by stevemessick**
This makes a few changes to the new project wizard.
- Use the --package-name option to pass the package name to `flutter create`
- Simplify the layout of the settings page, making it more compatible with Android Studio
  - Remove company domain
  - Make the package name a text field instead of a label that converts to a text field when edited
- Add some annotations

It also disallows committing project roots while the indexer is running.

Fixes #4352 

Screen Shot 2020-02-20 at 1 41 02 PM

### CODE REVIEW

File: src/io/flutter/sdk/FlutterCreateAdditionalSettings.java [hunk 1]
```diff
@@ -100,6 +113,11 @@ public void setKotlin(boolean value) {
       args.add(org);
     }
 
+    if (!StringUtil.isEmptyOrSpaces(project)) {
+      args.add("--project-name");
```
Comment (devoncarew) [inline src/io/flutter/sdk/FlutterCreateAdditionalSettings.java]: We should verify `--project-name` vs `--package-name`.

Comment (devoncarew) [reply src/io/flutter/sdk/FlutterCreateAdditionalSettings.java]: Looks like `--project-name`; this was added to flutter ~17 months ago (https://github.com/flutter/flutter/commit/b95b67a66b64c94f9bbe1c011bbfddb593a64429).
