### PR TITLE
Tolerate null elements in the outline visitor

### LINKED ISSUE #3737: NPEs from CommonTestConfigUtils.visit
```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.flutter.run.common.CommonTestConfigUtils.visit(CommonTestConfigUtils.java:159)
	at io.flutter.run.common.CommonTestConfigUtils.getTestsFromOutline(CommonTestConfigUtils.java:88)
	at io.flutter.run.common.CommonTestConfigUtils.findTestName(CommonTestConfigUtils.java:117)
	at io.flutter.run.test.FlutterTestConfigProducer.setupConfigurationFromContext(FlutterTestConfigProducer.java:59)
	at io.flutter.run.test.FlutterTe	
```

```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.flutter.run.common.CommonTestConfigUtils.visit(CommonTestConfigUtils.java:159)
	at io.flutter.run.common.CommonTestConfigUtils.visit(CommonTestConfigUtils.java:177)
	at io.flutter.run.common.CommonTestConfigUtils.visit(CommonTestConfigUtils.java:177)
	at io.flutter.run.common.CommonTestConfigUtils.visit(CommonTestConfigUtils.java:177)
	at io.flutter.run.common.CommonTestConfigUtils.visit(CommonTestConfigUtils.java:1	
```

### PR DESCRIPTION
**Pull request by DaveShuckerow**
Fixes #3737.

### CODE REVIEW

File: src/io/flutter/run/common/CommonTestConfigUtils.java [hunk 1]
```diff
@@ -156,7 +156,13 @@ protected ActiveEditorsOutlineService getActiveEditorsOutlineService(@NotNull Pr
    * Traverses the {@param outline} tree and adds to {@param callToTestType } the {@link DartCallExpression}s that are tests or test groups.
    */
   private void visit(@NotNull FlutterOutline outline, @NotNull Map<DartCallExpression, TestType> callToTestType, @NotNull PsiFile file) {
-    @NotNull final PsiElement element = Objects.requireNonNull(file.findElementAt(outline.getOffset()));
+    final PsiElement element = file.findElementAt(outline.getOffset());
```
Comment (jacob314) [inline src/io/flutter/run/common/CommonTestConfigUtils.java]: why is the outline out of sync? Aren't we applying checks to only use the outlines if the document and file have the same length? Perhaps the real fix is o make sure we are applying the conversion between editor file locations and intellij ones. On windows the lengths can be different.

Comment (jacob314) [reply src/io/flutter/run/common/CommonTestConfigUtils.java]: It would have stopped a couple similar bugs I had if we could make all the apis on the FlutterOutline match the IntelliJ notion of offsets rather than the Analyzer notion.
