### PR TITLE
Handle failed daemon processes better

### LINKED ISSUE #1008: Device list can become out of sync with extensive use
## Steps to Reproduce
I have yet to find a way to get reproduce this consistently, but it happens fairly often to me.  I test on several devices and emulators:
Devices: iPhone7, Gen 3 MotoX, Nexus 5
Simulator: iPhone SE, Pixel

After building enough times to some devices, at some point the device list will just stop updating.  I don't know what causes it exactly though.  But that's the use case.  Best advice I can give is try to build a complete app with flutter with several devices.    The issue can be fixed by restarting the IDE.

## Version info
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 5a9b525146 (4 days ago), 2017-05-05 11:27:15 -0700
    • Engine revision 0071651ecb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • Nexus 5X                  • 0106bcc49c8ca3eb                     • android-arm • Android 7.1.1 (API 25)
    • iPhone SE                 • 046CD453-58EF-4F20-9C95-CDD2713DFADC • ios         • iOS 10.3 (simulator)
```

### PR DESCRIPTION
**Pull request by skybrian**
- For occasional flakes, automatically restart
- For other unexpected failures, report as an IDE error so that
  it can be sent as a bug.

Fixes #1008

### CODE REVIEW

File: src/io/flutter/run/daemon/DeviceService.java [hunk 1]
```diff
@@ -159,6 +163,31 @@ private void refreshDeviceDaemon() {
...
+    final long millisSinceLastRestart = now - lastRestartTime.get();
+    if (millisSinceLastRestart > TimeUnit.MINUTES.toMillis(5)) {
+      LOG.info("A Flutter device daemon stopped. Automatically restarting it.\n" + details);
+      refreshDeviceDaemon();
+      lastRestartTime.set(now);
+      return;
+    }
+
+    // Report this so the user can send it to us, without restarting.
+    LOG.error("A Flutter device daemon stopped unexpectedly.\n" + details);
```
Comment (devoncarew) [inline src/io/flutter/run/daemon/DeviceService.java]: I believe you could also do `LOG.error("A Flutter device daemon stopped unexpectedly", details);`, which would pass the 2nd arg through as a 'details' param.

File: src/io/flutter/run/daemon/DeviceDaemon.java [hunk 2]
```diff
@@ -315,6 +362,15 @@ public void onDeviceRemoved(@NotNull DaemonEvent.DeviceRemoved event) {
       deviceChanged.run();
     }
 
+    @Override
+    public void processTerminated(int exitCode) {
+      if (running.get()) {
+        processStopped.accept(
+          "Daemon #" + daemonId + " exited. Exit code: " + exitCode + ". Stderr:\n" +
+          api.getStderrTail());
```
Comment (devoncarew) [inline src/io/flutter/run/daemon/DeviceDaemon.java]: Should we also clear out the ring buffer?

**Comment by devoncarew** [comment]
lgtm!

File: src/io/flutter/run/daemon/DeviceDaemon.java (hunk 2 above)
Comment (skybrian) [inline src/io/flutter/run/daemon/DeviceDaemon.java]: I don't think it's necessary; it will be garbage collected when we remove the last reference to the DeviceDaemon. 

A project should only reference one DeviceDaemon at a time, except transiently when the DaemonService is attempting to start a new one.

File: src/io/flutter/run/daemon/DeviceService.java (hunk 1 above)
Comment (skybrian) [inline src/io/flutter/run/daemon/DeviceService.java]: Done
