### PR TITLE
Fix 1391

### LINKED ISSUE #1391: Generated applicationId is wrongfully generated
The application ID is not properly reversed during the setup process of a new Flutter project in Android Studio.

## Steps to Reproduce
 During the setup process, the wizard is asking for the company domain: e.g. `example.com` and previewing the app ID as it's going to be generated: `com.example.my_flutter_app`.

image

The resulting app ID (and Java file structure) that is generated is: `example.com.myflutterapp`

image

## Version info

```bash
$ flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at D:\opt\flutter
    • Framework revision 4424892c79 (8 hours ago), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\dennis\AppData\Local\Android\sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: C:\Program Files\Android\Android Studio 3.0 Preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio 3.0 Preview
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[√] Connected devices
    • Nexus 6P • 8-----2 • android-arm • Android 8.0.0 (API 26)
```

### PR DESCRIPTION
**Pull request by stevemessick**
@devoncarew @pq 

(fix #1391)

### CODE REVIEW

File: flutter-studio/src/io/flutter/project/FlutterProjectCreator.java [hunk 1]
```diff
@@ -257,9 +257,17 @@ private FlutterCreateAdditionalSettings makeAdditionalSettings() {
...
       .setType(myModel.projectType().getValue())
-      .setOrg(myModel.packageName().get().isEmpty() ? null : myModel.packageName().get())
+      .setOrg(myModel.packageName().get().isEmpty() ? null : reversedOrgFromPackage(myModel.packageName().get()))
       .setKotlin(myModel.useKotlin().get() ? true : null)
       .setSwift(myModel.useSwift().get() ? true : null)
       .build();
   }
+
+  private static String reversedOrgFromPackage(@NotNull String packageName) {
+    int idx = packageName.lastIndexOf('.');
```
Comment (pq) [inline flutter-studio/src/io/flutter/project/FlutterProjectCreator.java]: Maybe make `idx` final?
