### PR TITLE
Stop running the Android framework detector

### LINKED ISSUE #989: 'Build Project' action doesn't work for flutter projects
_From @darrellpf on April 30, 2017 1:37_

## Steps to Reproduce

Make a new flutter project

Intellij says frameworks detected
  - configure
 - click Android manifest.xml
  - message is Android Facet added
Click the build button
Error : Android source generator : [Android] Android Manifest.xml file not found

## Flutter Doctor
```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision a4ba761bea (26 hours ago), 2017-04-28 16:01:14 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /home/darrell/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.4)
    • Android Studio at /home/darrell/android-studio
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424.10
    • Flutter plugin version 13.0

[✓] Connected devices
    • None
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

_Copied from original issue: flutter/flutter#9691_

### PR DESCRIPTION
**Pull request by stevemessick**
Creating a new project with IntelliJ caused a notification to appear (which disappeared before I could capture the image). I would click its "Configure" button then deselect the items in this window. 

Screen Shot 2020-10-23 at 3 17 08 PM

If you did nothing the notification would appear next time you open the project. If you allow the configuration to proceed your Android module is ruined.

This just stops the detector from running on Flutter projects.

Fixes #989

### CODE REVIEW

File: src/io/flutter/ProjectOpenActivity.java [hunk 1]
```diff
@@ -56,6 +59,7 @@ public void runActivity(@NotNull Project project) {
       // We can't do anything without a Flutter SDK.
       return;
     }
+    excludeAndroidFrameworkDetector(project);
```
Comment (devoncarew) [inline src/io/flutter/ProjectOpenActivity.java:62]: Do we want to do this every time we open the project, or once per project? We do do w few things just once per project (showing the 'flutter has hot reload' notification) - this might be a candidate for the same.

**Review by devoncarew — APPROVED** [review]

File: src/io/flutter/ProjectOpenActivity.java (hunk 1 above)
Comment (stevemessick) [reply src/io/flutter/ProjectOpenActivity.java:62]: It doesn't appear to be stored in project files.
