### PR TITLE
Refresh devices

### LINKED ISSUE #4208: Support refreshing the list of running devices
Provide a way to ask IntelliJ to refresh the list of Flutter devices manually.
There are some cases where the flutter daemon has crashed or is in a bad state so needs to be refreshed or restarted to get things back in a good state.

Closing and reopening the project in IntelliJ fixes the issue but is inconvenient.

### LINKED ISSUE #4801: Flutter Device Selection is not up to date
## Steps to Reproduce

* Open AVD Manager, create new device
* Flutter Device Selection doesn't show the newly created device
* Restart IntelliJ IDEA, the device appears

## Version info

> flutter doctor -v

[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-DE)
    • Flutter version 1.20.3 at ...\flutter
    • Framework revision 216dee60c0 (2 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at ...\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = ...\android-sdk
    • Java binary at: ...\java\jdk-1.8.0.212-3.b04.redhat\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-3-redhat-b04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] VS Code (version 1.48.2)
    • VS Code at ...\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

### LINKED ISSUE #5221: Reload supported device list when Flutter channel is changed in Preferences
## Steps to Reproduce

1.[make sure IntelliJ IDEA has stable channel as Flutter channel in Preferences]

Screen Shot 2021-01-28 at 11 47 31

2. make sure IDE is synced with that Flutter version in supported devices:
Screen Shot 2021-01-28 at 11 48 51

3. Now, go to Preferences and change the Flutter channel to Master and run (optional) `flutter pub get`.

Expected: Supported device list to be updated with the new selected channel.
Actual: Supported device list does not show all devices supported by the Master channel, I expect it to show Web and Desktop devices.

## Version info

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.229, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.26.0-13.0.pre.229 at /Users/pedromassango/Code/flutter_master
    • Framework revision 650b240634 (72 minutes ago), 2021-01-27 21:39:06 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by stevemessick**
Add a `Refresh` item to the device list. `DeviceService.isRefreshInProgress` was added to eliminate the flashing caused by the widget being hidden while the device service was inactive.

Screen Shot 2021-03-18 at 9 53 12 AM

Fixes #5221 
Fixes #4801 
Fixes #4208

To be fair, this is not the "fix" requested in some of those issues, but is a work-around for the problem described. Automatically updating the device list after a new emulator is created isn't practical. Alternatively, recreating the list every time it is shown isn't performant.

### CODE REVIEW

File: src/io/flutter/actions/DeviceSelectorAction.java [hunk 1]
```diff
@@ -67,9 +67,11 @@ public void update(final AnActionEvent e) {
 
     super.update(e);
 
-    Presentation presentation = e.getPresentation();
+    final Presentation presentation = e.getPresentation();
     if (!knownProjects.contains(project)) {
       knownProjects.add(project);
+      // TODO https://plugins.jetbrains.com/docs/intellij/disposers.html?from=jetbrains.org#choosing-a-disposable-parent
+      // Find a proper parent disposable. Projects and modules are never disposed.
```
Comment (helin24) [inline src/io/flutter/actions/DeviceSelectorAction.java:74]: Would listening for project closing instead be better here?

**Review by helin24 — APPROVED** [review]

File: src/io/flutter/actions/DeviceSelectorAction.java (hunk 1 above)
Comment (stevemessick) [reply src/io/flutter/actions/DeviceSelectorAction.java]: Good idea! Done.

**Comment by pedromassango** [comment]
@stevemessick what about reloading the device list once Flutter channel was changed in Preferences? I don't think this fixes https://github.com/flutter/flutter-intellij/issues/5221.

**Comment by stevemessick** [comment]
@pedromassango Correct. This is as close to a fix for #5221 as I have time for right now. At least there is a work-around so you don't have to re-open the project. #5222 is still open.
