### PR TITLE
Prevent bazel test run configurations from generating in a non-bazel workspace

### LINKED ISSUE #3169: Running/Debugging tests gives error "No Bazel target set"
Normally when Running or Debugging Flutter tests I have no issues. When you click Run or Debug the test should start as expected. Recently, this started happening.

## Steps to Reproduce
Run a test in one of the following ways. (Using Run or Debug)
- Right Click menu after right clicking on code in a test file.
- Right Click menu after right clicking on a file in a test folder in Project view
- Right Click menu after right clicking on a test in the Run window (Test Results)

## Steps to NOT Reproduce (works correctly this way)
- Right Click menu after right clicking a test folder in Project view

## Version info
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-CA)
    • Flutter version 1.1.8 at /Users/jrai/dev/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jrai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPad Air 2 • 5AD11829-1F07-439E-BA80-70CFDDB4B2A0 • ios • iOS 12.1 (simulator)

Here is a screenshot of what happens when I did: Right Click on job_manager_tests.dart > Run Tests
screen shot 2019-02-07 at 9 07 28 am

### PR DESCRIPTION
**Pull request by DaveShuckerow**
Fixes #3169

### CODE REVIEW

File: src/io/flutter/run/bazelTest/BazelTestConfigProducer.java [hunk 1]
```diff
@@ -30,9 +31,10 @@ protected BazelTestConfigProducer() {
     super(FlutterBazelTestConfigurationType.getInstance());
   }
 
-  private static boolean isFlutterContext(@NotNull ConfigurationContext context) {
+  private static boolean isBazelFlutterContext(@NotNull ConfigurationContext context) {
     final PsiElement location = context.getPsiLocation();
-    return location != null;
+    final Workspace workspace = Workspace.load(context.getProject());
```
Comment (devoncarew) [inline src/io/flutter/run/bazelTest/BazelTestConfigProducer.java]: DBC: I couldn't see how this worked initially, as I thought `Workspace` was something generic - perhaps IntelliJ related. In a future PR, we may want to rename to something like `BazelWorkspace` in order to better qualify the class.

Comment (DaveShuckerow) [reply src/io/flutter/run/bazelTest/BazelTestConfigProducer.java]: Noted.
