### PR TITLE
Show icons only for known sets

### LINKED ISSUE #5071: Android studio always show preview of MaterialIcons for IconData
Android studio always show preview of MaterialIcons for IconData
image

## Steps to Reproduce

Add a custom font in `pubspec.yaml` and define a `IconData`

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

I installed latest version of plugin (Ignore not installed in the following)

```dart
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (9 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\PC\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\PC\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

### PR DESCRIPTION
**Pull request by stevemessick**
Fixes #5071 

This adds a check to ensure an icon preview is only shown for the known, cached icons.

We plan to investigate showing custom icon previews soon. See #2334.

### CODE REVIEW

File: src/io/flutter/editor/FlutterIconLineMarkerProvider.java [hunk 1]
```diff
@@ -44,6 +62,18 @@
     PsiElement parent = refExpr.getParent();
     if (parent == null) return null;
 
+    // Resolve the class reference and check that it is one of the known, cached classes.
+    final PsiElement symbol = "IconData".equals(name) ? refExpr : refExpr.getFirstChild();
+    final PsiElement result = ((DartReference)symbol).resolve();
+    if (result == null) return null;
+    final List<VirtualFile> library = DartResolveUtil.findLibrary(result.getContainingFile());
+    if (library.size() > 1) return null;
```
Comment (helin24) [inline src/io/flutter/editor/FlutterIconLineMarkerProvider.java:70]: Is library size potentially 0?

**Review by helin24 — APPROVED** [review]

File: src/io/flutter/editor/FlutterIconLineMarkerProvider.java (hunk 1 above)
Comment (stevemessick) [reply src/io/flutter/editor/FlutterIconLineMarkerProvider.java]: Yes, apparently. I changed to a for-loop to check all possibilities.
