### PR TITLE
Run flutter channel if git is not available

### LINKED ISSUE #5232: Error getting Flutter sdk information. No such file: git.exe
-------

## What happened

nothing .. everything seems to be working fine 
just the IDE flagging this issue so i thought i submit it

## Version information

IntelliJ IDEA `2020.3.2` • Flutter plugin `io.flutter 53.0.5` • Dart plugin `203.6912`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.openapi.vcs.VcsException: Cannot Run Git: 
No such file: git.exe
	at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:152)
	at git4idea.commands.GitCommandResult.getOutputOrThrow(GitCommandResult.java:141)
	at git4idea.light.LightGitUtilKt.getLocation(LightGitUtil.kt:24)
	at io.flutter.sdk.FlutterSdk.queryFlutterChannel(FlutterSdk.java:515)
	at io.flutter.module.FlutterGeneratorPeer.lambda$fillSdkCache$1(FlutterGeneratorPeer.java:94)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
------

## Version info

flutter doctor :

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (6 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM G935F (mobile) • ce11160b55e0e81403 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
.

### PR DESCRIPTION
**Pull request by stevemessick**
There was no reason to log an error if `git` was not available. Now, we try running `flutter channel` if needed. It may have a better ability to find the channel, but if not it will still be classified as "unknown". Open question whether it should be "stable" instead. The channel is used to determine if platform selection should be shown when creating a new project.

Fixes #5232

### CODE REVIEW

File: src/io/flutter/sdk/FlutterSdkChannel.java [hunk 1]
```diff
@@ -63,4 +63,16 @@ public ID getID() {
   public String toString() {
     return "channel " + channel.toString();
   }
+
+  @NotNull
+  public static String parseChannel(@NotNull String text) {
+    String[] lines = text.split("\n");
```
Comment (helin24) [inline src/io/flutter/sdk/FlutterSdkChannel.java:69]: does this work for windows too?

**Review by helin24 — APPROVED** [review]

File: src/io/flutter/sdk/FlutterSdkChannel.java (hunk 1 above)
Comment (stevemessick) [reply src/io/flutter/sdk/FlutterSdkChannel.java:69]: Good catch; I'll have to check.
