### PR TITLE
Restore source compatibility for the product matrix

### LINKED ISSUE #3453: Does not work with IDEA 2019.1.2 RC
Basic functionality like autocompletion and highlighting doesn't work

image

```log
ERROR - yzer.DartAnalysisServerService - io.flutter.dart.FlutterDartAnalysisServer$$Lambda$863/755738588.onResponse(Ljava/lang/String;)V 
java.lang.AbstractMethodError: io.flutter.dart.FlutterDartAnalysisServer$$Lambda$863/755738588.onResponse(Ljava/lang/String;)V
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:863)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:700)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:48)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:1122)
```

## Version info

```
flutter doctor -v
[✓] Flutter (Channel master, v1.5.9-pre.149, on Mac OS X 10.14.4 18E226, locale en-RU)
    • Flutter version 1.5.9-pre.149 at /Users/maksimrv/www/dart/flutter
    • Framework revision 2f75005a16 (55 minutes ago), 2019-05-04 09:14:49 -0700
    • Engine revision 1d062db4db
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /usr/local/opt/android-sdk
      but Android SDK not found at this location.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2 RC)
    • IntelliJ at /Users/maksimrv/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 35.2.3
    • Dart plugin version 191.7222

[!] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 5 categories.
```

```
IntelliJ IDEA 2019.1.2 (Ultimate Edition)
Build #IU-191.7141.32, built on April 30, 2019
Licensed to JetBrains Team /  
Subscription is active until December 10, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
```

Flutter plugin v35.2.3
Dart plugin v191.7222 

[idea.log](https://github.com/flutter/flutter-intellij/files/3144615/idea.log)

### PR DESCRIPTION
**Pull request by stevemessick**
@devoncarew If we do a patch release this should be included.

1. ProjectOpenActivity requires a no-arg constructor. It was removed when someone added a single-arg constructor.

2. The analysis server listener needs to maintain compatibility with all usable versions of the Dart plugin.

Even if no one else touches the Android Studio sources I think others should be working with the sources from the intellij-community repository.

Fixes #3453

### CODE REVIEW

File: src/io/flutter/ProjectOpenActivity.java [hunk 1]
```diff
@@ -34,7 +34,9 @@
   public static final ProjectType FLUTTER_PROJECT_TYPE = new ProjectType("io.flutter");
   private static final Logger LOG = Logger.getInstance(ProjectOpenActivity.class);
 
-  @NotNull private final FlutterSettings settings;
+  private FlutterSettings settings;
```
Comment (devoncarew) [inline src/io/flutter/ProjectOpenActivity.java]: Perhaps mark this as `@Nullable`?

Comment (stevemessick) [reply src/io/flutter/ProjectOpenActivity.java]: Done. Compiling with the latest Dart plugin would have caught the other one of these problems.

Comment (stevemessick) [reply src/io/flutter/ProjectOpenActivity.java]: And undone, since it caused the build to go red.
