### PR TITLE
Use full path to studio on windows

### LINKED ISSUE #3585: INTELLIJ IDEA Exception when clicking on "Open for editing in Android Studio"
## Steps to Reproduce

**1.** Open any Android source file inside your FLUTTER PROJECT on INTELLIJ IDEA.

**2.** Click on the command "Open for Editing in Android Studio" at the top right of INTELLIJ IDEA Editor.

**You immediately get an IDE Error: "Exception: Cannot run program "C:\Program Files\Android\Android Studio": CreateProcess error=5, Access is denied".
And obviously nothing opens up.**

( please see attached screenshot of the error )

**Expected**: INTELLIJ IDEA launches Android Studio, opening this file.

I found a "workaround":

From the command prompt, if you change the FLUTTER config with:

**"flutter config --android-studio-dir PATH-TO-THE-ANDROID-STUDIO-EXECUTABLE-INSTEAD-OF-DIR"**

**making it pointing to the ANDROID STUDIO'S EXECUTABLE instead of the path dir, IT WORKS... and INTELLIJ launches ANDROID STUDIO correctly.**

But this can't be the right way of doing things... because this workaround "breaks" the flutter config.... causing flutter doctor to fail.

There must be sort of a bug somewhere... please investigate it.

## Version info

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Versione 10.0.17134.829], locale it-IT)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\aledi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7019

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[√] Connected device (1 available)

error

### PR DESCRIPTION
**Pull request by stevemessick**
Fixes #3585

### CODE REVIEW

File: src/io/flutter/actions/OpenInAndroidStudioAction.java [hunk 1]
```diff
@@ -151,6 +151,9 @@ private static void openFileInStudio(@NotNull VirtualFile projectFile, @NotNull
       }
       else {
         // TODO Open editor on sourceFile for Linux, Windows
```
Comment (devoncarew) [inline src/io/flutter/actions/OpenInAndroidStudioAction.java]: Should we adjust this TODO? I think it describes what this method is doing; we can perhaps delete the todo.

Comment (stevemessick) [reply src/io/flutter/actions/OpenInAndroidStudioAction.java]: The TODO is still valid. I plan to experiment to see if we can get a file to open, like with MacOS.
