### PR TITLE
Fix the lost SDK on start up problem

### LINKED ISSUE #5313: new projects are not picking up the Flutter SDK to use
New projects are no longer picking up the Flutter SDK to use; we'd previously discovered the correct flutter sdk setting by parsing the .packages file. This code still exists in the plugin, so we'll need to look into why this workflow regressed.

### PR DESCRIPTION
**Pull request by stevemessick**
Fixes #5313 

We used to use `DartPlugin.isDartSdkEnabled(module)` as a quick short-circuit for checking if the Flutter SDK was configured. That isn't reliable (not sure why) anymore. The result is that the first time a project is created after IntelliJ is launched, the project does not have its SDK configured. Projects created after the first one do, however.

This also adds support for the new `.dart_tool/package_config.json` file.

Since the Dart SDK is configured, I tried to find a way to determine its location on disk. You can see in External Libraries that it knows about its content, so the path has to be somewhere. The IntelliJ API does not appear to reveal that information.

@alexander-doroshko If you can take a minute to look at this I'd appreciate any tips on finding the Dart SDK on disk. This approach works, and seems fast enough, but I can't help thinking it is redundant.

### CODE REVIEW

File: src/io/flutter/utils/FlutterModuleUtils.java [hunk 1]
```diff
@@ -361,11 +361,7 @@ public static void setFlutterModuleAndReload(@NotNull Module module, @NotNull Pr
   }
 
   public static void enableDartSDK(@NotNull Module module) {
```
Comment (devoncarew) [inline src/io/flutter/utils/FlutterModuleUtils.java:363]: I just want to confirm that we don't try to set a flutter sdk if an sdk is already configured?

File: src/io/flutter/sdk/FlutterSdkUtil.java [hunk 2]
```diff
@@ -285,23 +328,35 @@ public static String parseFlutterSdkPath(String packagesFileContent) {
...
   }
 
+  private static String extractSdkPathFromUri(String urlString) {
+    if (urlString.startsWith("file:")) {
+      final Url url = Urls.parseEncoded(urlString);
+      if (url == null) {
+        return null;
+      }
+      final String path = url.getPath();
+      // go up three levels for .packages or two for .dart_tool/package_config.json
```
Comment (devoncarew) [inline src/io/flutter/sdk/FlutterSdkUtil.java:349]: We could also parameterize this method - the call site knows whether it's 2 deep or 3; either way would work.

**Review by devoncarew — APPROVED** [review]

File: src/io/flutter/sdk/FlutterSdkUtil.java (hunk 2 above)
Comment (stevemessick) [reply src/io/flutter/sdk/FlutterSdkUtil.java:349]: I agree that a parameter is better; changed.

File: src/io/flutter/sdk/FlutterSdkUtil.java [hunk 3]
```diff
@@ -254,12 +259,50 @@ public static void enableDartSdk(@NotNull final Project project) {
    */
   @Nullable
   public static String guessFlutterSdkFromPackagesFile(@NotNull Module module) {
+    // First, look for .dart_tool/package_config.json
     for (PubRoot pubRoot : PubRoots.forModule(module)) {
-      final VirtualFile packagesFile = pubRoot.getPackagesFile();
+      final VirtualFile packagesFile = pubRoot.getPackageConfigFile();
```
[the remark this answers is not in the document]
Comment (stevemessick) [reply src/io/flutter/sdk/FlutterSdkUtil.java:264]: If this were Kotlin, then yes. I think we're better off conforming to existing convention, like `getPackagesFile()`.

File: src/io/flutter/utils/FlutterModuleUtils.java (hunk 1 above)
Comment (stevemessick) [reply src/io/flutter/utils/FlutterModuleUtils.java:363]: Good point. I added a test to return immediately if `FlutterSdk.getFlutterSdk(module.getProject())` is not null. Confirmed that new projects do not return.

**Comment by stevemessick** [comment]
Added a patch to modify the JSON parsing for AF.3.1 -- we have 2.7 on the class path and it does not have #parseString.

File: src/io/flutter/sdk/FlutterSdkUtil.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (devoncarew) [reply src/io/flutter/sdk/FlutterSdkUtil.java:264]: Sorry - I was referring to the local variable name here - `final VirtualFile packageConfigFile` (not critical for the PR).

**Comment by alexander-doroshko** [comment]
@stevemessick Sorry, I'm offline until 3/29
